### ISSUE TITLE
Schema type error when rendering custom post block

### ISSUE THREAD

**Issue by davidvc** [thingsym/custom-post-type-widget-blocks#11]
When we use the Custom Post Types block to create a block from a custom post, we get this error when we try to render the page:

" Function rest_validate_value_from_schema was called incorrectly. The "type" schema keyword for term can only be one of the built-in types: array, object, string, number, integer, boolean, and null"

I printed out the call stack in the debug log, and this error is hit inside Wordpress, where it is validating a type specification against the list of valid types. The type coming in is "int" and WP only allows "integer" or "number."

Here is the gist for the full debug output: https://gist.github.com/davidvc/340992116c2b7f16e49e274b043372c9

**Comment by thingsym** [comment]
This issue is not about the Custom Post Type Widget Blocks plugin.
The plugin that corresponds to the issue is Custom Query Blocks.
https://ja.wordpress.org/plugins/post-type-archive-mapping/
